# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indgen_conn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='indgen_conn.proto',
  package='indgen_conn',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11indgen_conn.proto\x12\x0bindgen_conn\"\x16\n\x05Lemma\x12\r\n\x05lemma\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x03\x41\x63k\x12\x13\n\x0b\x61\x63k_message\x18\x01 \x01(\t2\x80\x01\n\x07Greeter\x12@\n\x08SayHello\x12\x19.indgen_conn.HelloRequest\x1a\x17.indgen_conn.HelloReply\"\x00\x12\x33\n\tSendLemma\x12\x12.indgen_conn.Lemma\x1a\x10.indgen_conn.Ack\"\x00\x62\x06proto3'
)




_LEMMA = _descriptor.Descriptor(
  name='Lemma',
  full_name='indgen_conn.Lemma',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lemma', full_name='indgen_conn.Lemma.lemma', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=56,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='indgen_conn.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='indgen_conn.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=86,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='indgen_conn.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='indgen_conn.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=117,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='indgen_conn.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack_message', full_name='indgen_conn.Ack.ack_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=145,
)

DESCRIPTOR.message_types_by_name['Lemma'] = _LEMMA
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lemma = _reflection.GeneratedProtocolMessageType('Lemma', (_message.Message,), {
  'DESCRIPTOR' : _LEMMA,
  '__module__' : 'indgen_conn_pb2'
  # @@protoc_insertion_point(class_scope:indgen_conn.Lemma)
  })
_sym_db.RegisterMessage(Lemma)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'indgen_conn_pb2'
  # @@protoc_insertion_point(class_scope:indgen_conn.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'indgen_conn_pb2'
  # @@protoc_insertion_point(class_scope:indgen_conn.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'indgen_conn_pb2'
  # @@protoc_insertion_point(class_scope:indgen_conn.Ack)
  })
_sym_db.RegisterMessage(Ack)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='indgen_conn.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=276,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='indgen_conn.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendLemma',
    full_name='indgen_conn.Greeter.SendLemma',
    index=1,
    containing_service=None,
    input_type=_LEMMA,
    output_type=_ACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
